baseURL = 'https://david.pilato.fr'
title = 'David Pilato'

languageCode = 'en-us'
defaultContentLanguage = "en"

theme = "dream"

enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
city = "cities"
language = "languages"

[params]
# zenMode = true
 
lightTheme = "emerald"
darkTheme = "forest"
 
# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""
 
images = ["me/background.jpg"]
 
author = "David Pilato"
description = "Developer | Evangelist"
avatar = "/about/david_pilato.avif"
headerTitle = "David Pilato"
motto = "Developer | Evangelist"

# footerBottomText = ""
 
rss = true
 
utterancesRepo = "dadoonet/dadoonet.github.io"
 
# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
 
# waline = true
# walineServer = ""
 
email = "david+blog@pilato.fr"
 
siteStartYear = 2010
 
favicon = "favicon.ico"
 
# Syntax highlighting
# customSyntaxHighlighting = true
 
# options
stickyNav = true
reorderNavItems = ["posts", "talks", "about_me"]
collapseNavItems = ["categories", "tags", "rss"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[params.navItems]
talks = { href = "/talks", icon = "mic", title = "Talks" }
about_me = { href = "/about", icon = "body", title = "About me" }

[params.icons]
online = "ðŸŒŽ"

[params.talks]
# PDF base URL for external storage (Google Cloud Storage)
pdf_base_url = "https://storage.googleapis.com/dadoonet-talks/slides/"

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []
 
[params.experimental]
#jsDate = true
#jsDateFormat = "yyyy/MM/dd"

#[services]
#[services.googleAnalytics]
#ID = "UA-62381049-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
