baseURL = 'https://david.pilato.fr'
title = 'David Pilato'

languageCode = 'en-us'
defaultContentLanguage = "en"

theme = "dream"

enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
city = "cities"
language = "languages"

[params]
# zenMode = true
 
lightTheme = "emerald"
darkTheme = "forest"

# PDF base URL for external storage (Google Cloud Storage)
pdf_base_url = "https://storage.googleapis.com/dadoonet-talks/slides/"
 
# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""
 
images = ["me/background.jpg"]
 
author = "David Pilato"
description = "Developer | Evangelist"
avatar = "/about/david_pilato.png"
headerTitle = "David Pilato"
motto = "Developer | Evangelist"

# footerBottomText = ""
 
rss = true
 
utterancesRepo = "dadoonet/dadoonet.github.io"
 
# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
 
# waline = true
# walineServer = ""
 
email = "david+blog@pilato.fr"
 
siteStartYear = 2010
 
favicon = "favicon.ico"
 
# Syntax highlighting
# customSyntaxHighlighting = true
 
# options
stickyNav = true
reorderNavItems = ["rss", "posts", "talks", "categories", "tags", "github", "x", "bluesky", "linkedin", "elastic", "podcast", "deejay"]
# collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[params.navItems]
talks = { href = "/talks", icon = "mic", title = "Talks" }
github = { href = "https://github.com/dadoonet", target = "_blank", icon = "logo-github", title = "GitHub" }
x = { href = "https://x.com/dadoonet", target = "_blank", icon = "logo-x", title = "X" }
bluesky = { href = "https://bsky.app/profile/pilato.fr", target = "_blank", icon = "logo-twitter", title = "BlueSky" }
linkedin = { href = "https://www.linkedin.com/in/dadoonet", target = "_blank", icon = "logo-linkedin", title = "Linkedin" }
elastic = { href = "https://elastic.co/", target="_blank", icon = "business", title = "Elastic" }
podcast = { href = "https://podcasts.apple.com/fr/podcast/dj-elky-mixes/id959495351", target="_blank", icon = "musical-notes", title = "Podcast DJ Elky" }
instagram = { href = "https://www.instagram.com/dj_elky/", target="_blank", icon = "logo-instagram", title = "DJ Elky" }

[params.icons]
online = "ðŸŒŽ"

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []
 
[params.experimental]
#jsDate = true
#jsDateFormat = "yyyy/MM/dd"

#[services]
#[services.googleAnalytics]
#ID = "UA-62381049-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
